import type { Metadata } from "next";
import { M_PLUS_2 } from "next/font/google";

import "remixicon/fonts/remixicon.css";
import "./globals.css";

const mplus2 = M_PLUS_2({
  weight: ["100", "200", "400", "500", "600", "700", "800", "900"],
  preload: false
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>){
  return (
    <html lang="ja">
      <body className={mplus2.className}>{children}</body>
    </html>
  );
}
